language: android

android:
  components:
    - build-tools-20.0.0
    - android-19

script:
  ./gradlew -u -p gandalf-library/ clean assembleDebug assembleDebugTest -x lint; ./gradlew -u -p gandalf-plugin/ clean build
